disabled_rules:
  - trailing_comma
opt_in_rules:
  - array_init
  - closure_spacing
  - closure_end_indentation
  - contains_over_first_not_nil
  - empty_count
  - explicit_init
  - first_where
  - joined_default_parameter
  - literal_expression_end_indentation
  - multiline_arguments
  - multiline_parameters
  - operator_usage_whitespace
  - sorted_imports
  - yoda_condition
included:
  - memorize
excluded:
  - Pods
  - init.swift
force_cast:
  severity: warning
force_try:
  severity: warning
line_length:
  warning: 101
  error: 120
type_body_length:
  warning: 300
  error: 400
file_length:
  warning: 500
  error: 850
function_parameter_count:
  warning: 6
  error: 8
function_body_length:
  warning: 25
  error: 32
cyclomatic_complexity:
  ignores_case_statements: true
  warning: 5
  error: 7
type_name:
  min_length:
    warning: 3
  max_length:
    warning: 40
    error: 50
  excluded: iPhone
  allowed_symbols: ["_"]
identifier_name:
  min_length:
    error: 3
  excluded:
    - id
    - URL
    - GlobalAPIKey
reporter: "xcode"
